# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'lolesports-calendar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lolesports-calendar
  pod 'Firebase/Core'
  pod 'Firebase/Functions'

  pod 'SDWebImage', '~> 5.0'
end
